In [7]:
import pandas as pd
import numpy as np
subjects = ['國文', '英文', '數學', '地理', '歷史']
scores = np.random.randint(50, 101, size=(50, 5))
scores_df = pd.DataFrame(scores, columns=subjects, index=range(1, 51))
scores_sum = scores_df.sum(axis=1)
scores_average = scores_df.mean(axis=1)
scores_df

     國文  英文   數學   地理   歷史
1    98  56   79   65   68
2    78  91   79   53   92
3    56  54   93   66   56
4    57  59   69   67   83
5    61  77   71   61   79
6    90  59   59   84   56
7    69  71  100   57   78
8    89  55   93   91   85
9    74  84   62   53   82
10   60  96   50   71   52
11   50  75   86   93   55
12   58  65   86   74   97
13   59  93   91   64   84
14   66  65   79   98   88
15   92  71   60   51   80
16   94  78   61   61   67
17   86  81   74   58   76
18   73  71   73   56   83
19  100  62   73   58   56
20   53  87   51   70   72
21   92  97   65   78   83
22   55  56   71   64   85
23   74  55   58   78   93
24   57  55   66   75   74
25   59  97   50   62   51
26   92  50   90   52   96
27   59  56   63   65   56
28   51  91   68   99   54
29   84  73   92   55   59
30   99  99   61   61   70
31   81  68   94   79   55
32   64  81   77   72   88
33   66  77   59   70   57
34   90  58   68   91  100
35   80  73   88   62   77
36   54  53   72   70   62
37   70  85   75   74   81
38   82  73   73   84   95
39   57  84   80   61   69
40   59  59  100  100   75
41   90  76   57   79   75
42   65  98   66   93   93
43   89  94   87   66   76
44   93  89   67   79   79
45   88  94   50   86   87
46   51  71   76   82   91
47   74  55   72   94   85
48   83  87   74   64   77
49   90  91   76   92   68
50   81  66   52   94   85

In [6]:
from pandas import Series
def to_statistic(value:Series)->Series:
    return Series([value.max(),value.min(),value.mean()],index=['最高分','最低分','平均分'])
scores_df.apply(to_statistic)

       國文     英文    數學     地理    歷史
最高分  99.0  99.00  99.0  99.00  98.0
最低分  50.0  50.00  51.0  50.00  51.0
平均分  76.0  75.94  75.9  71.56  75.7